<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageVersion Include="Microsoft.Extensions.Azure" Version="1.13.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2"/>
  </ItemGroup>
</Project>